export const kAppStates =  {
  INITIALIZATION: 'INITIALIZATION', // UNKNOWN STATE
  DESKTOP_MAIN: 'DESKTOP_MAIN',
  DESKTOP_AFTER_GAME: 'DESKTOP_AFTER_GAME',

  IN_GAME_QUESTION_SUGGESTION: 'IN_GAME_QUESTION_SUGGESTION',
  IN_GAME_QUESTION: 'IN_GAME_QUESTION',
  IN_GAME_HIDDEN: 'IN_GAME_HIDDEN', // Skipped, closed or autohidden.

  IN_NO_EVENTS_GAME_QUESTION_SUGGESTION: 'IN_NO_EVENTS_GAME_QUESTION_SUGGESTION',
  IN_NO_EVENTS_GAME_QUESTION: 'IN_NO_EVENTS_GAME_QUESTION',
  IN_NO_EVENTS_GAME_RETRY_PENDING: 'IN_NO_EVENTS_GAME_RETRY_PENDING',

  // LAUNCHED_MANUALLY: 'LAUNCHED_MANUALLY',
  // LAUNCHED_BY_GAME: 'LAUNCHED_BY_GAME',
};
