export const kEventKeys =  { // BusEventKeys
	APP_NETWORK_CHANGE: 'APP_NETWORK_CHANGE',
	HOTKEY_PRESSED: 'HOTKEY_PRESSED',
	UPDATE_TO_STATE: 'UPDATE_TO_STATE',
	STORE_DATA_UPDATE: 'STORE_DATA_UPDATE',
};
