export const kMetrics = {
    AppLoading_Ended: "AppLoading_Ended",
    View_PoppedUp: "View_PoppedUp",
    View_Closed: "View_Closed",
    QuestionSuggestion_ViewOpened: "QuestionSuggestion_ViewOpened",
    QuestionSuggestion_Accepted: "QuestionSuggestion_Accepted",
    QuestionSuggestion_Skipped: "QuestionSuggestion_Skipped",
    Question_ViewOpened: "Question_ViewOpened",
    Question_AnswerSelected: "Question_AnswerSelected",
    Question_CheckAnswer_ViewOpened: "Question_CheckAnswer_ViewOpened",
    Question_Flow_Completed: "Question_Flow_Completed",
    Raffles_ViewOpened: "Raffles_ViewOpened",
    Store_ViewOpened: "Store_ViewOpened",
    Store_BuyTicket_Clicked: "Store_BuyTicket_Clicked",
    HotkeysEditor_ViewOpened: "HotkeysEditor_ViewOpened",
    Collect_ViewOpened: "Collect_ViewOpened",
    PlayScreen_ViewOpened: "PlayScreen_ViewOpened",
    Settings_ViewOpened: "Settings_ViewOpened",
    Settings_Login_Clicked: "Settings_Login_Clicked",
    Settings_Start_Tutorial:"Settings_Start_Tutorial",
    Settings_ResetAppData_Clicked: "Settings_ResetAppData_Clicked",
    Settings_ResetAppData_Approved: "Settings_ResetAppData_Approved",
    Learn_ViewOpened: "Learn_ViewOpened",
    Faq_Expanded: "Faq_Expanded",
}
