export const kRepoKeys =  {
	AUTH_TOKEN: 'AUTH_TOKEN',
	AUTH_EXPIRATION: 'AUTH_EXPIRATION',
	FINISHED_ONBOARDING: 'FINISHED_ONBOARDING',
	LAST_QUIZ_SUGGESTION: 'LAST_QUIZ_SUGGESTION',
	// QUIZ_QUESTIONS: 'QUIZ_QUESTIONS'
	QUIZES_ACCEPTED: 'QUIZES_ACCEPTED',
	QUIZES_ACCEPTED_LAST_GAME: 'QUIZES_ACCEPTED_LAST_GAME',
	LAST_BONUS_QUIZ_SUGGESTED_AT: 'LAST_BONUS_QUIZ_SUGGESTED_AT',
	BONUS_QUIZ_MODE: 'BONUS_QUIZ_MODE',
	FAKE_GAME_ID: 'FAKE_GAME_ID',
	LAST_QUIZ_SKIPPED: 'LAST_QUIZ_SKIPPED',
	LAST_QUIZ_ANSWERED: 'LAST_QUIZ_ANSWERED',
	TUTORIAL_QUIZ_MODE: 'TUTORIAL_QUIZ_MODE',
};
